language: node_js
node_js:
- stable
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: WH8yPa8Y6W/lVyit2Xq2m76WwzHT5+aH/1g/xGyGkDC/m5VqVBKLb9cYlpMkYwsbzTt8EsKDzOXOd8OGB5OOmRrKW1C59gRaaISFLOJ7arA4B5OOCqi19VMTH8EmS/oHmU1aU+V1bXbkdFMsGeIAZnolNYYzJ22WQ/us9xJUK8kbK8kZEGbmiCEIEn7lDe6OEUINNl0FHMK0iPu/Qw33dvxCdQ7n+8QbGVYdNZqyFYJsx0zBXxQFqVtMR7dGru/jq4eZk8FoEu0rdmJnB7VK3FvGe5qz7QpMHH2GYFBBEQxv1r/6/BoKluQWLpGmn1h8Nv/8kPZwGtzXGhAY2gUUS6ZLW1m1XXpROlq1w+SPOEct1EKpA3b3IEpE/2Pgx28tqLZ02J28xntfwbW4/ElckrOt1C0zP+ONUbM0XErEwhZZMHGDe8mi3kxqdkK/c3SIqh2qrHCRqZsXC0e2SwsUF7NOUWTtL2vlwEPYe57F1xwkYaNsYsj6lByYW78wm3j1VLofec5pgaZwFmHW1w7ILbjIiK2XApFwSD/7OdQzqzdT7/7sRIc6T253epUUHVmZup8ZrHTBiCqH1jrisNYQ5Q4aQgbat0niU8ky8CyLEtD6TYoQWK/dAKAhrzxE8jffitIA0uMxDFefef4etd9xVgiTl7j66teTqU3ZdOY2twA=
  app:
    name: business-qard
  on:
    repo: jondam1985/business-QaRd
    branch: master
